### ISSUE TITLE
Not compatible with the latest vs code version

### ISSUE THREAD

**Issue by melkishengue** [lsl/vscode-templ-go-to-definition#1]
<img width="365" alt="image" src="https://github.com/user-attachments/assets/ef7bb7d0-7a8d-4601-8109-541d6e822ef0">

I get this while trying to install the extension. I' have the latest vscode version 1.90.0

**Comment by lsl** [comment]
https://github.com/lsl/vscode-templ-go-to-definition/commit/2bf7b6ebc7cc97987667432b689cfe3e5df82161, should work now.
